version: '3.9'

services:
  servidor:
    container_name: express-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./src:/server/src

  database:
    image: mariadb:latest
    container_name: mi-mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: dockerdb
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
